package finance.dtos;

public enum ErrorCode {
    NOT_FOUND,
    INTERNAL_ERROR,
    INSUFFICIENT_SHARES,
    INSUFFICIENT_FUNDS,
    INVALID_REQUEST,
    UNAUTHENTICATED,
    FORBIDDEN,
    REGISTRATION_FAILED,
    INVALID_CREDENTIALS,
    OPERATION_FAILED,
    OPERATION_PARTIALLY_FAILED,
    MALFORMED_REQUEST
}
